name: estu_attendance_admin
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  url_strategy: ^0.3.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^2.16.0

  user_repository:
    path: packages/user_repository
  course_repository:
    path: packages/course_repository
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
